[project]
name = "test-fastapi-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi-mcp>=0.2.0",
    "uvicorn>=0.34.1",
]
